CREATE TABLE worker
(
  ID       INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME     CHARACTER(1000) not null,
  BIRTHDAY DATE CHECK (YEAR(BIRTHDAY) > 1900),
  LEVEL    CHARACTER(20)   NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
  SALARY   INTEGER CHECK (Salary >= 100 AND Salary <= 100000),
  CONSTRAINT name_length_check CHECK (LENGTH(NAME) >= 2)
);

CREATE TABLE client
(
  ID   INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME CHARACTER(1000) not null,
  CONSTRAINT name_length_check_client CHECK (LENGTH(NAME) >= 2)
);

CREATE TABLE project
(
  ID          INTEGER PRIMARY KEY AUTO_INCREMENT,
  CLIENT_ID   INTEGER,
  START_DATE  date,
  FINISH_DATE date,
  FOREIGN KEY (CLIENT_ID) REFERENCES client (ID)
);

CREATE TABLE project_worker
(
  PROJECT_ID INTEGER,
  WORKER_ID  INTEGER,
  PRIMARY KEY (PROJECT_ID, WORKER_ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES project (ID),
  FOREIGN KEY (WORKER_ID) REFERENCES worker (ID)
);